
default: &default
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: SQLserver2010
  timeout: 25
  host: zeus

development:
  <<: *default
  database: despacho_development


report_db_development:
  <<: *default
  database:   acoma

test:
  <<: *default
  database: despacho_development

production:
  <<: *default
  database: despacho_production
