default: &default
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: SQLserver2011
  timeout: 25


development:
  <<: *default
  host: zeus
  database: despacho_development


report_db_development:
  <<: *default
  dataserver: ZEUS
  database: acoma

test:
  <<: *default
  host: zeus
  database: despacho_development

production:
  <<: *default
  host: zeus
  database: despacho_production
